/**
 * A 160 × 116, one-bit raster derived from the existing public
 * `echelon-assets/logo dots orange.png` asset. The orange source is
 * intentionally rendered as black for thermal paper.
 */
export const ECHELON_LOGO_WIDTH = 160;
export const ECHELON_LOGO_HEIGHT = 116;
export const ECHELON_LOGO_RASTER_BASE64 =
  "AAAAAAAAAAAAAAAAHwAAAAAD4AAAAAAAAAAAAAAAAAD/4AAAAB/8AAAAAAAAAAAAAAAAA//4AAAAf/8AAAAAAAAAAAAAAAAP//4AAAH//8AAAAAAAAAAAAAAAB///wAAA///4AAAAAAAAAAAAAAAP///gAAH///wAAAAAAAAAAAAAAB////AAA////gAAAAAAAAAAAAAAH///8AAD///+AAAAAAAAAAAAAAA////4AAf///8AAAAAAAAAAAAAAD////gAB////wAAAAAAAAAAAAAAf////AAP////gAAAAAAAAAAAAAB////8AA////+AAAAAAAAAAAAAAH////wAD////4AAAAAAAAAAAAAA/////gAP////wAAAAAAAAAAAAAD////+AB/////AAAAAAAAAAAAAAP////4AH////8AAAAAAAAAAAAAA/////gAf////wAAAAAAAAAAAAAD////+AA/////AAAAAAAAAAAAAAH////wAD////4AAAAAAAAAAAAAAf////AAP////gAAAAAAAAAAAAAB////8AA////+AAAAAAAAAAAAAAD////gAB////wAAAAAAAAAAAAAAP///+AAH////AAAAAAAAAAAAAAAf///wAAP///4AAAAAAAAAAAAAAB////AAA////gAAAAAAAAAAAAAAD///4AAB///8AAAAAAAAAAAAAAAH///AAAD///gAAAAAAAAAAAAAAAP//4AAAH//8AAAAAAAAAAAAAAAAP/+AAAAH//AAAAAAAAAAAAAAAAAP/gAAAAH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/AAAAAA/gAAAAAAAAAAAAAAAAA//gAAAAf/wAAAAAAAAAAAAAAAAP//gAAAH//wAAAAAAAAAAAAAAAB///AAAA///gAAAAAAAAAAAAAAAP//+AAAH///AAAAAAAAAAAAAAAB///8AAA///+AAAAAAAAAAAAAAAP///4AAH///8AAAAAAAAAAAAAAB////wAA////4AAAAAAAAAAAAAAH////AAD////gAAAAAAAAAAAAAA////+AAf////AAAAAAAAAAAAAAD////4AB////8AAAAAAAAAAAAAAP////gAH////wAAAAAAAAAAAAAA////+AAf////AAAAAAAAAAAAAAH////8AD////+AAAAAAAAAAAAAAf////wAP////4AAAAAAAAAAAAAB/////AA/////gAAAAAAAAAAAAAH////8AD////+AAAAAAAAAAAAAAP////gAH////wAAAAAAAAAAAAAA////+AAf////AAAAAAAAAAAAAAD////4AB////8AAAAAAAAAAAAAAP////gAH////wAAAAAAAAAAAAAAf///8AAP///+AAAAAAAAAAAAAAB////wAA////4AAAAAAAAAAAAAAD///+AAB////AAAAAAAAAAAAAAAH///wAAD///4AAAAAAAAAAAAAAAP//+AAAH///AAAAAAAAAAAAAAAAf//wAAAP//4AAAAAAAAAAAAAAAA//+AAAAf//AAAAAAAAAAAAAAAAA//gAAAAf/wAAAAAAAAAAAAAAAAA/4AAAAAf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+AAAAAf/AAAAAAAAAAAAAAAAAP/+AAAAH//AAAAAAAAAAAAAAAAD//8AAAA//+AAAAAAAAAAAAAAAAf//8AAAP//+AAAAAAAAAAAAAAAD///4AAB///8AAAAAAAAAAAAAAAf///wAAP///4AAAAAAAAAAAAAAB////AAA////gAAAAAAAAAAAAAAP///+AAH////AAAAAAAAAAAAAAA////4AAf///8AAAAAAAAAAAAAAH////wAD////4AAAAAAAAAAAAAAf////AAP////gAAAAAAAAAAAAAB////8AA////+AAAAAAAAAAAAAAP////wAH////8AAAAAAAAAAAAAA/////gAf////wAAAAAAAAAAAAAD////+AB/////AAAAAAAAAAAAAAP////4AH////8AAAAAAAAAAAAAA/////gAf////wAAAAAAAAAAAAAB////8AA////+AAAAAAAAAAAAAAH////wAD////4AAAAAAAAAAAAAAf////AAP////gAAAAAAAAAAAAAB////8AA////+AAAAAAAAAAAAAAD////gAB////wAAAAAAAAAAAAAAP///8AAH///+AAAAAAAAAAAAAAAf///wAAP///4AAAAAAAAAAAAAAA///+AAAf///AAAAAAAAAAAAAAAB///wAAA///4AAAAAAAAAAAAAAAD//+AAAB///AAAAAAAAAAAAAAAAH//wAAAD//4AAAAAAAAAAAAAAAAH/8AAAAD/+AAAAAAAAAAAAAAAAAB8AAAAAA+AAAAAAAAAAAAAAAAA==";

type EposLogoRasterCandidate = {
  width: number;
  height: number;
  base64: string;
};

const BASE64_PATTERN = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/;

function base64Bytes(value: string): Uint8Array {
  if (!BASE64_PATTERN.test(value)) {
    throw new Error("Echelon ePOS logo raster must be valid Base64.");
  }
  return Uint8Array.from(atob(value), (character) => character.charCodeAt(0));
}

export function validateEchelonLogoRaster(
  candidate: EposLogoRasterCandidate = {
    width: ECHELON_LOGO_WIDTH,
    height: ECHELON_LOGO_HEIGHT,
    base64: ECHELON_LOGO_RASTER_BASE64,
  },
): void {
  if (
    !Number.isInteger(candidate.width) ||
    !Number.isInteger(candidate.height) ||
    candidate.width <= 0 ||
    candidate.height <= 0 ||
    candidate.width % 8 !== 0
  ) {
    throw new Error("Echelon ePOS logo width must be byte-aligned.");
  }
  const bytes = base64Bytes(candidate.base64);
  const expectedBytes = (candidate.width / 8) * candidate.height;
  if (bytes.length !== expectedBytes) {
    throw new Error("Echelon ePOS logo raster does not match its declared geometry.");
  }
  if (bytes.every((byte) => byte === 0)) {
    throw new Error("Echelon ePOS logo raster must contain at least one black pixel.");
  }
}

validateEchelonLogoRaster();
