export {
  COMPARATOR_SEMANTICS,
  COMPATIBILITY_CHANGE_KINDS,
  COMPATIBILITY_RULES,
  SOURCE_ENVELOPE_SCHEMA_VERSION,
  SOURCE_ENVELOPE_VOCABULARY_MIGRATION,
  V1_VOCABULARY,
} from "./compatibility";
export type {
  CompatibilityChangeKind,
  EnvelopeVocabulary,
} from "./compatibility";

export {
  assessCompatibility,
  extractPgEnumLabels,
  liveEnvelopeVocabulary,
  runContractsCheck,
} from "./check";
export type {
  CompatibilityChange,
  CompatibilityVerdict,
  ContractsCheckResult,
} from "./check";

export {
  CanonicalIdentitySchema,
  DerivedContextRevisionSchema,
  FingerprintInputsSchema,
  FingerprintScalarSchema,
  OPTIONAL_ENVELOPE_FIELDS,
  PG_ENUM_LABELS,
  RELATIONSHIP_SCOPES,
  REQUIRED_ENVELOPE_FIELDS,
  REQUIRED_IDENTITY_FIELDS,
  REQUIRED_RESOURCE_SLOT_FIELDS,
  RESOURCE_PRESENCES,
  RelationshipScopeEntrySchema,
  RelationshipScopeSchema,
  ResourcePresenceSchema,
  ResourceSlotSchema,
  SOURCE_APPLY_RESULTS,
  SOURCE_ENVELOPE_KINDS,
  SourceApplyResultSchema,
  SourceEnvelopeKindSchema,
  SourceEnvelopeSchema,
  SourceVersionEntrySchema,
} from "./source-envelope";
export type {
  CanonicalIdentity,
  DerivedContextRevision,
  FingerprintInputs,
  RelationshipScope,
  RelationshipScopeEntry,
  ResourcePresence,
  ResourceSlot,
  SourceApplyResult,
  SourceEnvelope,
  SourceEnvelopeKind,
  SourceVersionEntry,
} from "./source-envelope";

export {
  allSetupSlotsProven,
  CLASSIFICATION_ALLOWLIST,
  CLASSIFICATION_ALLOWLIST_ORIGINS,
  CLASSIFICATION_CONFIG_STATUSES,
  CLASSIFICATION_DEFAULT_MODE,
  CLASSIFICATION_DISPLAY_LABEL_KINDS,
  CLASSIFICATION_DISPLAY_LABELS,
  CLASSIFICATION_MAPPING_CONFIG_MIGRATION,
  CLASSIFICATION_MODES,
  CLASSIFICATION_PG_ENUM_LABELS,
  CLASSIFICATION_SCHEMA_VERSION,
  CLASSIFICATION_SETUP_FIXTURE_KINDS,
  CLASSIFICATION_SETUP_SLOTS,
  CLASSIFICATION_SOURCE_PATH,
  AllowlistEntryProvenanceSchema,
  ClassificationAllowlistOriginSchema,
  ClassificationConfigStatusSchema,
  ClassificationDisplayLabelKindSchema,
  ClassificationModeSchema,
  ClassificationProvenanceSchema,
  ClassificationSetupFixtureKindSchema,
  ClassificationSourceSchema,
  DisplayOnlyProductGroupLabelSchema,
  isSetupSlotProven,
  liveClassificationSource,
  ProductGroupAllowlistSchema,
  SetupSlotFixturesSchema,
  SetupSlotSchema,
  TARGETED_UNPROVEN_MESSAGE,
  UNPROVEN_SETUP_FIXTURES,
  V1_CLASSIFICATION_SOURCE,
  V1_SETUP_SLOTS,
} from "./classification-config";
export type {
  AllowlistEntryProvenance,
  ClassificationAllowlistOrigin,
  ClassificationConfigStatus,
  ClassificationDisplayLabelKind,
  ClassificationMode,
  ClassificationProvenance,
  ClassificationSetupFixtureKind,
  ClassificationSource,
  DisplayOnlyProductGroupLabel,
  ProductGroupAllowlist,
  SetupSlot,
  SetupSlotFixtures,
} from "./classification-config";

export { runClassificationContractsCheck } from "./classification-check";
